custom_text_center=Press F1 to hide / Press F2 to position
toggle_hud=F1
toggle_hud_position=F2

legacy_layout=false
round_corners=10
background_alpha=0.4
position=top-left
background_color=000000
no_display

gpu_stats
gpu_temp
cpu_stats
cpu_temp
ram
swap
fps
engine_short_names